export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ERROR_FETCHING_PRODUCTS = 'ERROR_FETCHING_PRODUCTS'
export const SHOW_DETAILS = 'SHOW_DETAILS'
export const ERROR_SHOWING_DETAILS   = 'ERROR_SHOWING_DETAILS'
export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'